version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html

  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data

  webapp:
    image: jfahrer/demo_web_app:latest
    ports:
      - 9292:9292
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST

  alpine:
    image: alpine:latest
    stdin_open: true
    tty: true
    command: sh

volumes:
  pg-data:
