# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'cadvisor'
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.cadvisor'
  #     type: 'A'
  #     port: 8080

  # - job_name: 'node-exporter'
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.node-exporter'
  #     type: 'A'
  #     port: 9100

  # - job_name: 'docker-exporter'
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.docker-exporter'
  #     type: 'A'
  #     port: 4999
